### PR TITLE
Allow override of valid-variables

### PR DESCRIPTION
**Pull request by brazorf**

### CODE REVIEW

**Comment by denissimon** [comment]
Default valid variables cannot be overwritten in such a way.

**Comment by brazorf** [comment]
Why not?

**Comment by denissimon** [comment]
It would break the code that rely on these variables.

**Comment by brazorf** [comment]
Not that i'm testing in depth, however i am using the library with this feature enabled without bugs.
Can you provide an example that would break the code?

**Comment by denissimon** [comment]
Well, with that implementation it’s possible to set multiple characters or some of these symbols: +, -, *, /, ^ as a valid variable. It can cause to unexpected error. Besides, "e" is always handled by parser as a constant = 2.718, even though there is a variable with the same name.

So, I can suggest to add an additional check for these conditions in the top of getResult(). If an error occurs, should be returned the message "Variable error" ($this->error_type = 4). 
If that is ok, I'll reopen your pull request.

**Comment by brazorf** [comment]
Ok got your point now. I'll try to find some time to make a new commit.

**Pull request merged**
